apiVersion: v1
kind: Pod
metadata:
  name: git-repo-pod
spec:
  initContainers:
    - name: git-clone
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --
        - https://github.com/lisnayk/k8n-lec6-example.git
        - /repo
      volumeMounts:
        - name: html-content
          mountPath: /repo
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-content
      emptyDir: {}