apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
spec:
  containers:
  - name: log-viewer
    image: busybox
    command: ["sh", "-c", "tail -f /node-logs/syslog || tail -f /node-logs/messages"]
    volumeMounts:
    - name: node-logs
      mountPath: /node-logs
      readOnly: true
  volumes:
  - name: node-logs
    hostPath:
      path: /var/log
      type: Directory