apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-monitor.fullname" . }}
  labels:
    {{- include "k8s-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-monitor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-monitor.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: STUDENT_NAME
          value: {{ .Values.student.name | quote }}
        - name: STUDENT_GROUP
          value: {{ .Values.student.group | quote }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
