apiVersion: v1
kind: Pod
metadata:
  name: sa-test-pod
  namespace: development
spec:
  serviceAccountName: build-robot
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "3600"]
