apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
spec:
  containers:
    - name: web
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: generator
      image: debian:12-slim
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh","-c"]
      args:
        - "while true; do echo \"<html><head><title>Live Time</title><style>body{font-family:Arial,sans-serif;background:#f0f0f0;text-align:center;padding:50px;}h1{color:#333;}p{font-size:1.2em;color:#555;}</style></head><body><h1>Pod: multicontainer</h1><p>Container: WBB </p><p>Current time: <b>$(date +\"%Y-%m-%d %H:%M:%S\")</b></p></body></html>\" > /html/index.html; sleep 1; done"
  volumes:
    - name: html
      emptyDir: {}
