apiVersion: v1
kind: Pod
metadata:
  name: demo-web
spec:
  containers:
    - name: web
      image: munspel/ubuntu-nginx-htop:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "25m"
          memory: "32Mi"
        limits:
          cpu: "30m"
          memory: "64Mi"
