apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-app
  name: nginx-app
spec:
  containers:
  - image: nginx
    name: nginx-app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
