apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: frontend
spec:
  containers:
    - name: hello1
      image: munspel/ubuntu-nginx-htop:latest
      resources:
        requests:
          cpu: "25m"
          memory: "32Mi"
        limits:
          cpu: "30m"
          memory: "64Mi"