apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: staging
data:
  APP_ENV: "staging"
  MEMCACHED_SERVERS: "memcached-service.staging.svc.cluster.local:11211"
  APP_COLOR: "#e3f2fd" # Light blue for staging
  EXTERNAL_API_URL: "http://external-api-service.staging.svc.cluster.local:3001/api/external/data"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-api-secret
  namespace: staging
stringData:
  API_KEY: "staging-external-key-111"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: staging
stringData:
  API_KEY: "staging-api-key-789"
  DB_PASSWORD: "staging-password"
  EXTERNAL_API_KEY: "staging-external-key-111"
