apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-node-viewer
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes-globally
subjects:
- kind: ServiceAccount
  name: my-app-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: global-node-viewer
  apiGroup: rbac.authorization.k8s.io
