apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: docker.io/bitnamisecure/memcached:latest
          ports:
            - containerPort: 11211
          command:
            - memcached
            - -m 220
            - -o
            - modern
            - -I 20M
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: MEMCACHED_PORT_NUMBER
              value: '11211'
