apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  APP_ENV: "production"
  MEMCACHED_SERVERS: "memcached-service.prod.svc.cluster.local:11211"
  APP_COLOR: "#ffe0b2" # Light orange for production
  EXTERNAL_API_URL: "http://external-api-service.prod.svc.cluster.local:3001/api/external/data"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-api-secret
  namespace: prod
stringData:
  API_KEY: "prod-external-key-999"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
stringData:
  API_KEY: "prod-api-key-123-super-secret"
  DB_PASSWORD: "very-strong-prod-password"
  EXTERNAL_API_KEY: "prod-external-key-999"
